name: muslim_pocket_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/lotties/
    - assets/prayers/
    - assets/quran/
    - assets/tafsir/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400

