import 'package:get/get.dart';

class FeatTafsirController extends GetxController {
  final List<String> quranSurahList = [
    "1. Al Fatihah (Pembuka)",
    "2. Al Baqarah (Sapi Betina)",
    "3. Ali Imran (Keluarga Imran)",
    "4. An Nisa (Wanita)",
    "5. Al Ma'idah (Jamuan)",
    "6. Al An'am (Hewan Ternak)",
    "7. Al-A'raf (Tempat yang Tertinggi)",
    "8. Al-Anfal (Harta Rampasan Perang)",
    "9. At-Taubah(Pengampunan)",
    "10. Yunus (Nabi Yunus)",
    "11. Hud (Nabi Hud)",
    "12. Yusuf (Nabi Yusu)",
    "13. Ar-Ra'd (Guruh)",
    "14. Ibrahim (Nabi Ibrahim)",
    "15. Al-Hijr (Gunung Al Hijr)",
    "16. An-Nahl (Lebah)",
    "17. Al-Isra' (Perjalanan Malam)",
    "18. Al-Kahf (Penghuni-penghuni Gua)",
    "19. Maryam (Maryam)",
    "20. Ta Ha (Ta Ha)",
    "21. Al-Anbiya (Nabi-Nabi)",
    "22. Al-Hajj (Haji)",
    "23. Al-Mu'minun (Orang-orang mukmin)",
    "24. An-Nur (Cahaya)",
    "25. Al-Furqan (Pembeda)",
    "26. Asy-Syu'ara' (Penyair)",
    "27. An-Naml (Semut)",
    "28. Al-Qasas (Kisah-kisah)",
    "29. Al-'Ankabut (Laba-laba)",
    "30. Ar-Rum (Bangsa Romawi)",
    "31. Luqman (Keluarga Luqman)",
    "32. As-Sajdah (Sajdah)",
    "33. Al-Ahzab (Golongan-golongan yang Bersekutu)",
    "34. Saba' (Kaum Saba')",
    "35. Fatir (Pencipta)",
    "36. Ya Sin (Yaasiin)",
    "37. As-Saffat (Barisan-barisan)",
    "38. Sad (Shaad)",
    "39. Az-Zumar (Rombongan-rombongan)",
    "40. Ghafir (Yang Mengampuni)",
    "41. Fussilat (Yang Dijelaskan)",
    "42. Asy-Syura (Musyawarah)",
    "43. Az-Zukhruf (Perhiasan)",
    "44. Ad-Dukhan (Kabut)",
    "45. Al-Jasiyah (Yang Bertekuk Lutut)",
    "46. Al-Ahqaf (Bukit-bukit Pasir)",
    "47. Muhammad (Nabi Muhammad)",
    "48. Al-Fath (Kemenangan)",
    "49. Al-Hujurat (Kamar-kamar)",
    "50. Qaf (Qaaf)",
    "51. Az-Zariyat (Angin yang Menerbangkan)",
    "52. At-Tur (Bukit)",
    "53. An-Najm (Bintang)",
    "54. Al-Qamar (Bulan)",
    "55. Ar-Rahman (Yang Maha Pemurah)",
    "56. Al-Waqi'ah (Hari Kiamat)",
    "57. Al-Hadid (Besi)",
    "58. Al-Mujadilah (Wanita yang Mengajukan Gugatan)",
    "59. Al-Hasyr (Pengusiran)",
    "60. Al-Mumtahanah (Wanita yang Diuji)",
    "61. As-Saff (Satu Barisan)",
    "62. Al-Jumu'ah (Hari Jum'at)",
    "63. Al-Munafiqun (Orang-orang yang Munafik)",
    "64. At-Tagabun (Hari Dinampakkan Kesalahan-kesalahan)",
    "65. At-Talaq (Talak)",
    "67. Al-Mulk (Kerajaan)",
    "68. Al-Qalam (Pena)",
    "69. Al-Haqqah (Hari Kiamat)",
    "70. Al-Ma'arij (Tempat Naik)",
    "71. Nuh (Nabi Nuh)",
    "72. Al-Jinn (Jin)",
    "73. Al-Muzzammil (Orang yang Berselimut)",
    "74. Al-Muddassir (Orang yang Berkemul)",
    "75. Al-Qiyamah (Kiamat)",
    "76. Al-Insan (Manusia)",
    "77. Al-Mursalat (Malaikat-Malaikat Yang Diutus)",
    "78. An-Naba' (Berita Besar)",
    "79. An-Nazi'at (Malaikat-Malaikat Yang Mencabut)",
    "80. 'Abasa (Ia Bermuka Masam)",
    "81. At-Takwir (Menggulung)",
    "82.Al-Infitar (Terbelah)",
    "83. Al-Tatfif (Orang-orang yang Curang)",
    "84. Al-Insyiqaq (Terbelah)",
    "85. Al-Buruj (Gugusan Bintang)",
    "86. At-Tariq (Yang Datang di Malam Hari)",
    "87. Al-A'la (Yang Paling Tinggi)",
    "88. Al-Gasyiyah (Hari Pembalasan)",
    "89. Al-Fajr (Fajar)",
    "90. Al-Balad (Negeri)",
    "91. Asy-Syams (Matahari)",
    "92. Al-Lail (Malam)",
    "93. Ad-Duha (Waktu Matahari Sepenggalahan Naik (Dhuha))",
    "94. Al-Insyirah (Melapangkan)",
    "95. At-Tin (Buah Tin)",
    "96. Al-'Alaq (Segumpal Darah)",
    "97. Al-Qadr (Kemuliaan)",
    "98. Al-Bayyinah (Pembuktian)",
    "99. Az-Zalzalah (Kegoncangan)",
    "100. Al-'Adiyat (Berlari Kencang)",
    "101. Al-Qari'ah (Hari Kiamat)",
    "102. At-Takasur (Bermegah-megahan)",
    "103. Al-'Asr (Masa)",
    "104. Al-Humazah (Pengumpat)",
    "105. Al-Fil (Gajah)",
    "106. Quraisy (Suku Quraisy)",
    "107. Al-Ma'un (Barang-barang yang Berguna)",
    "108. Al-Kausar (Nikmat yang Berlimpah)",
    "109. Al-Kafirun (Orang-orang Kafir)",
    "110. An-Nasr (Pertolongan)",
    "111. Al-Lahab (Gejolak Api)",
    "112. Al-Ikhlas (Ikhlas)",
    "113. Al-Falaq (Waktu Subuh)",
    "114.An-Nas (Umat Manusia)",
  ];


}
